

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t39-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  tls:
  - hosts:
    - api39.my-points.ru
    - web39.my-points.ru
    - insights39.my-points.ru
    secretName: serverpod-tls-t39
  rules:
  - host: "api39.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t39-server-service
            port:
              name: api
  - host: "web39.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t39-server-service
            port:
              name: web
  - host: "insights39.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t39-server-service
            port:
              name: insights
    